version: "3.4"

services:
    web: 
        container_name: restwithaspnetudemy
        image: restwithaspnetudemy
        environment:
          - PORT=5000
        ports:
          - 5000:5000
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on:
          - db
        networks: 
          - udemy-network
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
          SA_PASSWORD: ""
          ACCEPT_EULA: "Y"
        networks: 
          - udemy-network
networks:
  udemy-network:
    driver: bridge

