version: "3.4"

services:
    restwithaspnetudemy: 
        container_name: restwithaspnetudemy
        image: restwithaspnetudemy
        environment:
          - PORT=5000
        ports:
          - 5000:5000
        build: 
            context: .
            dockerfile: Dockerfile